### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by h4m5t** [universuen/3_body#1]

**Comment by universuen** [comment]
@h4m5t Sorry for providing you an unfinished project at the time you opened this issue. Fortunately, it is now finished and you can run `main.py` to see the fantastic result!
By the way, if you are using Pycharm, do remember to **cancel** the following option.
![image](https://user-images.githubusercontent.com/52519513/107127262-f6155e00-68ef-11eb-865f-ca3c260f816d.png)

**Comment by h4m5t** [comment]
OK，thank you ,let me have a try!
